### ISSUE TITLE
More incompatible PICTs

### ISSUE THREAD

**Issue by andrews05** [TheDiamondProject/Graphite#21]
I was checking out [Galaxy's Edge](https://s3-us-west-2.amazonaws.com/ambrosiaevn/addons/evo/GalaxysEdge.sit.bin) and had some crashes while trying to parse some of the PICTs.
Some of the ones in the ships file appear to be comprised of multiple `direct_bits_rect` opcodes. Some refactoring would be required to support combining these into a single surface.
Some of the ones in the media file seem to have a different issue which I haven't looked into too much.

**Comment by tjhancocks** [comment]
I knew this would eventually be required, but kinda hoped I could avoid until after Kestrel ships.

**Comment by andrews05** [comment]
Fixed in #22.
(I’m sure it doesn’t cover everything but it fixes these ones at least)
