### ISSUE TITLE
Mismatch second preamble on some classic applications

### ISSUE THREAD

**Issue by CouleeApps** [TheDiamondProject/Graphite#32]
Notably, [Cro-Mag Rally](http://www.pangeasoft.net/cromag/demo.html), has an invalid second preamble on its resource map. Instead of containing a copy of the resource file preamble, it simply has zeroes, and fails [these checks in classic.cpp](https://github.com/TheDiamondProject/Graphite/blob/master/libGraphite/rsrc/classic.cpp#L53). I'm not sure of a correct solution for verifying resource maps, but if you remove the `throw` statements the app loads successfully.

**Comment by tjhancocks** [comment]
Sorry for not responding to this until now... I rarely come into this repo and I didn't get notified about the issue 🤔.

Looking into it I can only find one of the file types in the game that is actually a Resource Fork, the `.sounds` files. Most of the data files seem to be an archive of some sort, though I would need to do some investigation to find out what archive it is. I've actually noticed this with a few Pangea titles and it's possible that they have their own internal format for dealing with game data.

The question will likely end up being, should Graphite support every archive/data format found in Classic MacOS, even if they are not specific to the system themselves?

**Comment by tjhancocks** [comment]
I'm leaving the issue open as it poses an interesting question about the extent Graphite. The Diamond Project aims to make all Classic Software compatible on any modern system by emulating the environment so that the software can run there.

Games are necessarily already going to have the capability to read their own custom formats that their data is in, meaning that this may not serve any useful purpose.

On the other hand a modern clone of the game may need this archive.

**Comment by CouleeApps** [comment]
Specifically, I was trying to read the game executable itself. See here in ResForge with the patch I mentioned: 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/711973/132083472-c856776d-d765-422f-845c-dc0a2cedeb11.png">

As for the custom archive/data formats used in CMR, that's your decision but I would suggest letting the games handle their own custom data types.

**Comment by tjhancocks** [comment]
Sorry, forgot to actually check the Resource Fork of the main application. I checked it's data fork which just includes the standard PPC PEFF data.

The checks are required to actually ensure that we only try to run a Resource file through the parser. As they don't have a standardised extension, mime or type & creator code we can't do anything else to help here.

So the preamble copy in this case is fully zero'd so we may be to check if the preambles match _or_ if the second one is zero, as well as the file contents being the correct length according to the first preamble. If the second (back up) preamble doesn't match and isn't fully zero then it's unlikely to be a resource file.
